# Generated by Django 4.2.7 on 2023-11-24 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_color_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='title',
        ),
    ]
