# Generated by Django 4.2.7 on 2023-11-24 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_color_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='title',
            field=models.CharField(default='__', max_length=100),
        ),
    ]
