# Generated by Django 4.2.7 on 2023-11-24 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_variant_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='height',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='size',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='weight',
        ),
    ]
