# Generated by Django 4.2.7 on 2023-11-24 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_variant_height_remove_variant_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='brand',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.brand'),
        ),
    ]
