# Generated by Django 4.2.7 on 2023-11-24 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_variant_brand_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchased_times',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
